version: '3'

services:
  redis:
    image: redis
    networks:
    - deployml_network

  modelserver:
    image: editsync/modelserver
    build: ./modelserver
    depends_on:
    - redis
    networks:
    - deployml_network
    env_file:
    - app.env
    environment:
    - SERVER_SLEEP=0.25  # Time in ms between each poll by model server against Redis
    - BATCH_SIZE=32 # max batch size in parallel for each queue
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility]

  webserver:
    image: editsync/webserver
    build: ./webserver
    ports:
    - "80:80"
    networks:
    - deployml_network
    depends_on:
    - redis
    env_file:
    - app.env
    environment:
      - CLIENT_SLEEP=0.25  # Time in  between each poll by web server against Redis
      - CLIENT_MAX_TRIES=100  # Num tries by web server to retrieve results from Redis before giving up
      # - MAXWORKERS=2 # limit the number of slaves for fastapi
    # volumes:
    #     - ./webserver:/app
        
    #auto refresh for deployment
    #command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--debug", "--port", "80", "--reload-dir", "/app"]

networks:
    deployml_network:
